### PR TITLE
OnlineInstallerScript: use correct file extension

### PR DESCRIPTION
**Pull request by plata**
required by #231

### CODE REVIEW

**Comment by madoar** [comment]
Is it always the case, that the file contains a single `.`?
If not it would be useful to maybe split on the first `.`

**Comment by plata** [comment]
Why should I split on the first `.`? I need the file extension. Maybe the URL is something `abc.def.exe`.

**Comment by madoar** [comment]
You're right maybe the first `.` is not the best choice, but what do you do if you have a file with an `.tar.gz` ending for example?

**Comment by plata** [comment]
I don't know. Doesn't make a lot of sense to call a `.tar.gz` with Wine anyways. You probably have to extract it first and do some custom handling, so you would have to implement something in `preInstall`.

**Comment by madoar** [comment]
@plata This contains a conflict

**Pull request merged**
