### PR TITLE
allow to set Windows version in custom installer

### PR DESCRIPTION
**Pull request by plata**
fixes PlayOnLinux/POL-POM-5#540

### CODE REVIEW

**Comment by qparis** [comment]
I'm really not convinced that quick script should have all wine properties. preInstall and' postInstall is the right thing to handle this

**Comment by plata** [comment]
Don't think that's possible. Wine needs to know architecture, version etc when you call `prefix()`.

**Comment by plata** [comment]
Could do the Windows version in the `preInstall` but would be strange to handle this one setting differently than the others.

**Comment by qparis** [comment]
Which others?

**Comment by plata** [comment]
architecture, version, distribution

**Comment by qparis** [comment]
Those are POL settings, this is totally different.
You have hundred of wine settings (windows version, sound driver, dll overrides, glsl, etc...). It is just impossible to have setters for each of them

**Comment by plata** [comment]
I put it to preInstall.

**Pull request merged**
