### PR TITLE
Fix wineArchitecture regression (fixes #120)

### LINKED ISSUE #120: regression: .wineArchitecture does not change the architecture anymore
Caused by either https://github.com/PlayOnLinux/Scripts/commit/58d4e261f5a71fe9648f0f9f251cff5f78c5066c or https://github.com/PlayOnLinux/Scripts/commit/141c5f8e2dc382a2452fc62fbe880b44a87c3aad

### PR DESCRIPTION
**Pull request by Brainzyy**
Fixes #120

### CODE REVIEW

**Comment by qparis** [comment]
The code is not correct, I think we should handle the same way the distribution is handled

**Comment by Brainzyy** [comment]
@qparis Alright, [this issue](https://github.com/PlayOnLinux/POL-POM-5/issues/426) should probably be investigated as well then.

**Comment by plata** [comment]
@Brainzyy could you change the PR to:

```javascript
if (!this._architecture) {
    this._architecture = this._prefixConfiguration.readValue("wineArchitecture", "x86");
}
```

And remove
```javascript
this._architecture = "x86";
```
in the constructor.

I think that is what @qparis has in mind.

**Comment by Brainzyy** [comment]
@plata I fucked something up, I'll open a new PR.

**Pull request closed without merging**
