### PR TITLE
Update Steam July 2017

### PR DESCRIPTION
**Pull request by chriamue**
Steam is crashing since last Steam update.
Some crashes in net.cpp as described on this website: https://forum.level1techs.com/t/wine-crashes/117565
I did test wine staging 2.12 and it is working.
Tested only the Game AOE 2.

### CODE REVIEW

**Comment by plata** [comment]
This issue should be fixed in 2.0.2 (latest stable version). Therefore I think that this pull request will be obsolete after merging #304. Could you verify if that is correct?

**Comment by chriamue** [comment]
Yes it will be obsolete. Tested Steam on 2.0.2 stable.

**Comment by madoar** [comment]
I think we need to check all steam applications for their used wine version...
I believe we have some applications, that set a wine version manually...

**Comment by plata** [comment]
@madoar that's correct.

**Pull request closed without merging**
