### PR TITLE
Star Wars EAW Gold Pack

### PR DESCRIPTION
**Pull request by ImperatorS79**
The local version often need this fix for multyplayer and FOC->https://community.pcgamingwiki.com/files/download/188-star-wars-empire-at-war-2-gb-ram-mp-lobby-fix/

But I don't know how to add it in the script...

### CODE REVIEW

**Comment by plata** [comment]
You probably want a `postInstall` (see [wiki](https://github.com/PlayOnLinux/Scripts/wiki/script.js#advanced) step where you download the patch using the [Downloader](https://github.com/PlayOnLinux/Scripts/blob/master/Functions/Net/Download/script.js). Checkout the [Enderal script](https://github.com/PlayOnLinux/Scripts/blob/master/Games/Enderal/Steam/script.js) to get an idea how it's done.

**Comment by plata** [comment]
Why did you add the patch as a new script? Wouldn't it be better to have it as part of the Steam script?

**Comment by ImperatorS79** [comment]
Now, when i add a local repo with the script to test it, the testing checkbox seems to be unusable

**Comment by ImperatorS79** [comment]
The Steam script doesn't need the patch, only DVD version needs it

**Comment by plata** [comment]
Is your software up to date? The 4 level namespace requires an update there.

Ok, if it's only for the DVD version, then it's fine. Is it possible to install the DVD version from Phoenicis PlayOnLinux directly?

**Comment by ImperatorS79** [comment]
1) I have just rebuilt to take the change into account

2) I don't understand what you mean. I'm using a local installer script to select the setup on the DVD

**Comment by plata** [comment]
2. My idea is to provide a quick script which automatically runs the install from a DVD. I don't know if that's possible.

**Comment by ImperatorS79** [comment]
The problem is that the way the program is installed from a DVD can change. You need to find where is located the setup.exe. In my case, there is 2 setup.exe in two directories, one for the game and one for the expansion pack. so that I'm using the LauncherEAW.exe, to access both setup.exe

**Comment by plata** [comment]
Ok. Anyways this is out of scope for this PR.

**Comment by ImperatorS79** [comment]
Should I open a bug for the local repo problem ?

**Comment by plata** [comment]
Yes, if you have a problem open an issue.

**Comment by ImperatorS79** [comment]
@plata you will have to move my script from Games/Star Wars... to the new location in Application

**Pull request merged**
