### PR TITLE
Change WineShortcut to make use of the new method getMainMiniature() in ApplicationDTO

### PR DESCRIPTION
**Pull request by madoar**
Needs PlayOnLinux/POL-POM-5#854 to be merged.

### CODE REVIEW

**Comment by plata** [comment]
Do you have the rights to merge into the Scripts repository by now?

**Comment by madoar** [comment]
No, I don't have the rights to merge or approve.

**Comment by plata** [comment]
@qparis can you change that?

**Comment by madoar** [comment]
I think you can merge this. Afterwards we should test this "patch", because I couldn't test it yet.

**Pull request merged**
