### PR TITLE
STAR WARS Jedi Knight: fixed compatibleOperatingSystems

### PR DESCRIPTION
**Pull request by plata**
testing must be a subset of compatible

### CODE REVIEW

**Comment by plata** [comment]
Which one is missing?

**Comment by ImperatorS79** [comment]
All of them

**Comment by plata** [comment]
I don't get it. I have changed it for 
* STAR WARS Jedi Knight - Jedi Academy
* STAR WARS Jedi Knight - Mysteries of the Sith
* STAR WARS Jedi Knight II - Jedi Outcast
* STAR WARS Jedi Knight: Dark Forces II

So how can all Jedi Knight games be missing?

**Comment by ImperatorS79** [comment]
Sorry, didn't see you changed it for all those games...

**Comment by plata** [comment]
@madoar I've opened an issue for that: PlayOnLinux/POL-POM-5#959

**Pull request merged**
