### PR TITLE
Add game Unholy Heights

### PR DESCRIPTION
**Pull request by madoar**

### CODE REVIEW

**Comment by plata** [comment]
Can you add the German translation?

**Comment by madoar** [comment]
This game seems to have no german description on steam...

**Comment by plata** [comment]
Can you translate it yourself?

**Comment by plata** [comment]
You have to generate the translation files again because I've merged the sorting stuff.

**Comment by plata** [comment]
Sorry, you have to merge master again because I merged my PRs. If you do it now, I'll merge this.

**Pull request merged**
