### PR TITLE
Allow to set OS per application

### PR DESCRIPTION
**Pull request by plata**
fixes: #65

### CODE REVIEW

**Comment by plata** [comment]
I followed the example of `OverrideDLL()`. However, I don't quite understand why it is done this way. To use it, you have to write:
```javascript
wine.setOsForApplication().set("Notepad++.exe", "win7").do();
```
Why can't it be a simple function which could be used like:
```javascript
wine.setOsForApplication("Notepad++.exe", "win7");
```

**Comment by plata** [comment]
I think I understand now. It's because it allows you to set multiple overrides at once, right?

**Comment by qparis** [comment]
Yeah exactly ! Don't forget that we now have beans to parse and generate .reg files

**Comment by qparis** [comment]
I'll review your code when I am home

**Comment by plata** [comment]
Didn't know about the beans. In this case, probably the code for OS per application, sound driver and DLL override should be rewritten. I guess it would be the best to do everything in RegistryWinePrefixConfiguration.java directly so it can be used also from other UIs.

Can we merge OS per application and sound driver as they are and create an issue to do that in PoL 5?

**Pull request merged**
