### PR TITLE
EA Origin

### PR DESCRIPTION
**Pull request by plata**
* Local seems to be stuck in an endless loop during the update
* Online installs but crashes when starting it (OriginWebHelperService.exe and OriginClientService.exe)

### CODE REVIEW

**Comment by madoar** [comment]
So both scripts are currently broken?
Should we add them or wait until they somehow work?

**Comment by plata** [comment]
We should leave the PR open for now. I just wanted to share it as a base for discussion.

**Comment by plata** [comment]
The legacy script is working if I do the `postInstall` steps manually. @qparis am I doing something wrong with the extract or so?

**Comment by qparis** [comment]
it does not seem so

**Comment by madoar** [comment]
Don't we have a similar problem with the League of Legends script as described in #179, where you can install LoL manually but not through POL5?

**Comment by plata** [comment]
I just looked at the folder during the installation. It's actually working! But: The extracted files only appear in the folder after the installation is long finished. How can that possibly happen?

**Comment by madoar** [comment]
Just to be sure, are we talking about the `zip` extract or another extract here?

**Comment by plata** [comment]
Yes, the `zip` extract with `Extractor`. 

Just figured out that I cannot even show a message in `postInstall` (with the `wizard`). Like the installation is aborted already (maybe because there is an error in the setup?).

**Comment by plata** [comment]
Ok. So the installation is not aborted. Just the wizard is closed already.

**Comment by plata** [comment]
I've tracked it down: The wizard crashes/is closed when the `WineShortcut` is created. If I remove that step, everything is ok. Any ideas what could go wrong there?

**Comment by madoar** [comment]
No sry :/
If I remember correctly, the creation of a `WineShortcut` relies on both java and javascript code, right?

**Comment by plata** [comment]
Yes. You cannot really debug that code, that's really an issue.

**Comment by madoar** [comment]
The question that I'm asking myself is, are all exceptions/errors that occur in javascript printed in the terminal/console?

**Comment by plata** [comment]
I'm not sure. At least the printouts are. I simply have no idea why the wizard is closed by the shortcut creation.

**Comment by madoar** [comment]
Is it possible, that the `Extractor` terminates before all files are fully extracted?

**Comment by plata** [comment]
No. I just debugged a bit: The wizard is still running but not visible anymore because for some reason the tab got closed already.

**Comment by madoar** [comment]
What happens if the progress reaches `100%`?

**Comment by plata** [comment]
Don't know.

Anyways: `ViewLibrary#drawContent` is called. Therefore the tab is gone.

**Comment by plata** [comment]
And this is triggered when the shortcut is created.

**Comment by madoar** [comment]
So both scripts are working now?

**Comment by plata** [comment]
No the online one is still broken (it's not the legacy version). Also, I would like to add translations and an online script for the legacy version. I only have the problem that the link is somehow strange (www.dm.origin.com/download/legacy) and cannot be downloaded by our `Downloader`.

**Comment by madoar** [comment]
Ok, please give us a hands up if you think this is ready to be merged

**Comment by plata** [comment]
Sure.

**Comment by plata** [comment]
@qparis how can I download `www.dm.origin.com/download/legacy` with `Downloader`?

**Comment by plata** [comment]
Forget it. I found the real link.

**Comment by plata** [comment]
This can be merged now. The legacy versions (online + local) are working. The other one is set to "testing" (cannot work currently due to a wine bug).

**Pull request merged**
