### PR TITLE
Add DirectX 10

### LINKED ISSUE #276: DirectX 10
Can we add a verb for directx 10?
I need it for http://store.steampowered.com/app/342620/.
I'm not sure if this will help run the game, but at least some seems to got it working (https://www.reddit.com/r/linux_gaming/comments/3jyecw/what_are_some_of_the_best_games_you_can_run_in/)

### PR DESCRIPTION
**Pull request by madoar**
This PR fixes #276.
I used https://github.com/Winetricks/winetricks/blob/master/src/winetricks and https://github.com/PlayOnLinux/Scripts/blob/master/Functions/Verbs/d3dx9/script.js as a guideline.

### CODE REVIEW

**Comment by plata** [comment]
I guess we should wait until #279 is working before we merge this?

**Comment by madoar** [comment]
I think we should merge this anyhow. It gives script developers a way to use directx10.
Even if #279 doesn't work, this script can still be used, right?

**Comment by plata** [comment]
Yes, but how can we know if the Verb works?

**Comment by madoar** [comment]
We can only know this, if we have a script that works and requires directx 10.
But still if we don't merge this, we force other developers to reimplement this later on, which for new script developers is a large barrier and may possibly discourage them.

**Comment by plata** [comment]
Ok.

**Pull request merged**
