### PR TITLE
Ether One Redux: use wine stable

### PR DESCRIPTION
**Pull request by plata**

### CODE REVIEW

**Comment by plata** [comment]
The Steam game overlay needs to be disabled. Otherwise you get texture bugs.

@qparis can this be done in PoL? If not, how do we communicate this?

**Comment by qparis** [comment]
In POLv5, we could do 
 POL_Wine_OverrideDLL "" "gameoverlayrenderer"

**Comment by plata** [comment]
Can we add that functionality to SteamScript as `gameOverlay()`? 
To be used like:
```javascript
SteamScript.gameOverlay(false)
```

**Comment by qparis** [comment]
sure

**Pull request merged**
